[build]
  base = "frontend"
  publish = "frontend/out"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  PNPM_FLAGS = "--shamefully-hoist"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production" 