[build]
  base = "frontend"
  publish = "out"
  command = "corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install --shamefully-hoist --production=false && pnpm run build"

[build.environment]
  NODE_VERSION = "20"
  COREPACK_ENABLE_STRICT = "0"
  NODE_ENV = "development"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production" 